name: "publish"

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            args: ""
            name: linux
            arch: x86_64
            artifact_name_suffix: linux-x64
            package_extension: tar.gz
            os_runner: ubuntu-latest
          - platform: windows-latest
            args: ""
            name: windows
            arch: x86_64
            artifact_name_suffix: windows-x64
            package_extension: zip
            os_runner: windows-latest
          - platform: windows-latest
            args: "--target aarch64-pc-windows-msvc"
            name: windows
            arch: aarch64
            artifact_name_suffix: windows-arm64
            package_extension: zip
            os_runner: windows-latest
          - platform: macos-latest
            args: "--target aarch64-apple-darwin"
            name: macOS
            arch: aarch64
            artifact_name_suffix: macos-arm64
            package_extension: tar.gz
            os_runner: macos-14
          - platform: macos-latest
            args: "--target x86_64-apple-darwin"
            name: macOS
            arch: x86_64
            artifact_name_suffix: macos-x64
            package_extension: tar.gz
            os_runner: macos-latest
          # - platform: macos-latest
          #   args: "--target universal-apple-darwin"
          #   name: macOS
          #   arch: universal

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        name: clone repo
        with:
          fetch-depth: 0

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: setup rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: |
            wasm32-unknown-unknown,${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || (matrix.platform == 'windows-latest' && matrix.arch == 'aarch64') && 'aarch64-pc-windows-msvc' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            libappindicator3-dev \
            libwebkit2gtk-4.1-dev \
            librsvg2-dev \
            patchelf \
            curl \
            unzip \
            tar

      - name: "macOS: install llvm&clang"
        uses: KyleMayes/install-llvm-action@v2
        if: matrix.platform == 'macos-latest'
        with:
          version: "20"

      - name: "macOS: set env"
        if: matrix.platform == 'macos-latest'
        run: |
          SDK_PATH=$(xcrun --show-sdk-path)
          echo "SDK Path: $SDK_PATH"
          echo "BINDGEN_EXTRA_CLANG_ARGS=-isysroot $SDK_PATH" >> $GITHUB_ENV
        shell: bash

      - name: install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "v0.13.1"

      - name: build soa
        run: |
          pnpm i --frozen-lockfile --ignore-scripts
          pnpm nx build soa

      - name: generate dev version
        run: node scripts/gen-dev-version.mjs

      - name: build tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: soa-v__VERSION__ # the action automatically replaces __VERSION__ with the app version from tauri.conf.json
          releaseName: "soa v__VERSION__"
          releaseBody: |
            ☺️ Latest ${{ github.ref_name }} branch development build.
            Development version may be unstable and may not work properly, please only for test purpose.
            Latest commits: ${{ github.event.head_commit.message }}
          prerelease: true
          args: ${{ matrix.args }}

      - name: upload Action Artifact
        uses: actions/upload-artifact@v4
        with:
          name: soa ${{matrix.name}}-${{matrix.arch}}
          path: |
            /src-tauri/target/**/release/bundle/**/*
            /src-tauri/target/**/release/soa.exe
            /src-tauri/target/**/release/soa
